/**
 * News Feed Types
 *
 * Unified schema for all news articles regardless of source.
 * NPCs consume this feed with no distinction between real and fake content.
 */

// ============================================================================
// Source Types
// ============================================================================

/**
 * Where the article came from
 * - rss: External RSS feed (real news)
 * - user: Hand-crafted lore article
 * - ai: Generated by the story generator
 */
export type NewsSource = 'rss' | 'user' | 'ai';

/**
 * Article categories
 */
export type NewsCategory =
  | 'local'
  | 'tech'
  | 'entertainment'
  | 'politics'
  | 'business'
  | 'opinion'
  | 'sports'
  | 'science'
  | 'lifestyle';

/**
 * Sentiment classification
 */
export type NewsSentiment = 'positive' | 'negative' | 'neutral';

// ============================================================================
// Article Schema
// ============================================================================

/**
 * AI generation metadata (only for source: 'ai')
 */
export interface AIGenerationMetadata {
  triggerType: 'trending_topic' | 'npc_activity' | 'scheduled' | 'event';
  triggerData: {
    topic?: string;
    npcId?: string;
    activityType?: string;
    mentions?: number;
    posts?: string[];  // Post IDs that triggered this
  };
  generatedAt: number;
  model?: string;
  promptTokens?: number;
  completionTokens?: number;
}

/**
 * Core news article schema
 * All sources use this exact structure
 */
export interface NewsArticle {
  // Identity
  id: string;
  slug: string;  // URL-friendly identifier

  // Source tracking (internal only - NPCs don't see this distinction)
  source: NewsSource;
  sourceUrl?: string;      // Original RSS URL if applicable
  sourceFeed?: string;     // Feed name (e.g., 'reuters', 'ap')

  // Content
  headline: string;
  subheadline?: string;
  summary: string;         // 1-2 sentence summary for feed display
  content: string;         // Full article body (markdown)

  // Metadata
  category: NewsCategory;
  author: string;          // Byline (can be fake)
  publishedAt: number;     // Unix timestamp (ms)
  updatedAt?: number;

  // Media
  imageUrl?: string;
  imageCaption?: string;
  imageEmoji?: string;     // Fallback emoji if no image

  // Classification
  tags: string[];          // For topic matching
  entities: string[];      // Named entities (people, places, orgs)
  sentiment?: NewsSentiment;

  // Engagement tracking
  npcMentions: number;     // How many NPCs referenced this
  lastMentionedAt?: number;

  // AI generation metadata (only for source: 'ai')
  generatedFrom?: AIGenerationMetadata;

  // Timestamps
  createdAt: number;
}

// ============================================================================
// RSS Feed Configuration
// ============================================================================

export interface RSSFeedConfig {
  id: string;
  name: string;
  url: string;
  category: NewsCategory;
  refreshInterval: number;    // Minutes between fetches
  maxArticles: number;        // Max to keep per feed
  enabled: boolean;

  // Optional filtering
  includeKeywords?: string[]; // Only include if matches
  excludeKeywords?: string[]; // Skip if matches

  // Status
  lastFetchedAt?: number;
  lastError?: string;
}

// ============================================================================
// NPC News Exposure Tracking
// ============================================================================

/**
 * Tracks which articles an NPC has "seen" in their context
 */
export interface NPCNewsExposure {
  id: string;
  npcId: string;
  articleId: string;
  exposedAt: number;
  mentioned: boolean;  // Did they reference it in a post?
}

// ============================================================================
// Trending Topic Detection
// ============================================================================

export interface TrendingTopic {
  topic: string;
  mentions: number;
  posts: Array<{
    id: string;
    npcId: string;
    npcName: string;
    content: string;
    timestamp: number;
  }>;
  sentiment: NewsSentiment | 'mixed';
  firstMentionedAt: number;
  lastMentionedAt: number;
}

// ============================================================================
// Service Options
// ============================================================================

export interface GetHeadlinesOptions {
  limit?: number;
  categories?: NewsCategory[];
  sources?: NewsSource[];
  hoursBack?: number;
  excludeArticleIds?: string[];
  npcId?: string;  // For interest-based filtering
}

export interface SearchArticlesOptions {
  limit?: number;
  categories?: NewsCategory[];
  sources?: NewsSource[];
  fromDate?: number;
  toDate?: number;
}

export interface DetectTrendsOptions {
  hoursBack?: number;
  minMentions?: number;
  excludeTopics?: string[];
}

// ============================================================================
// API Response Types
// ============================================================================

export interface NewsFeedResponse {
  articles: NewsArticle[];
  total: number;
  hasMore: boolean;
}

export interface RSSRefreshResult {
  success: number;
  failed: number;
  newArticles: number;
  errors: Array<{ feedId: string; error: string }>;
}

// ============================================================================
// Database Row Types (for SQLite mapping)
// ============================================================================

export interface NewsArticleRow {
  id: string;
  slug: string;
  source: string;
  source_url: string | null;
  source_feed: string | null;
  headline: string;
  subheadline: string | null;
  summary: string;
  content: string;
  category: string;
  author: string;
  published_at: number;
  updated_at: number | null;
  image_url: string | null;
  image_caption: string | null;
  image_emoji: string | null;
  tags: string;  // JSON array
  entities: string;  // JSON array
  sentiment: string | null;
  npc_mentions: number;
  last_mentioned_at: number | null;
  generated_from: string | null;  // JSON object
  created_at: number;
}

/**
 * Convert database row to NewsArticle
 */
export function rowToArticle(row: NewsArticleRow): NewsArticle {
  return {
    id: row.id,
    slug: row.slug,
    source: row.source as NewsSource,
    sourceUrl: row.source_url ?? undefined,
    sourceFeed: row.source_feed ?? undefined,
    headline: row.headline,
    subheadline: row.subheadline ?? undefined,
    summary: row.summary,
    content: row.content,
    category: row.category as NewsCategory,
    author: row.author,
    publishedAt: row.published_at,
    updatedAt: row.updated_at ?? undefined,
    imageUrl: row.image_url ?? undefined,
    imageCaption: row.image_caption ?? undefined,
    imageEmoji: row.image_emoji ?? undefined,
    tags: JSON.parse(row.tags || '[]'),
    entities: JSON.parse(row.entities || '[]'),
    sentiment: row.sentiment as NewsSentiment | undefined,
    npcMentions: row.npc_mentions,
    lastMentionedAt: row.last_mentioned_at ?? undefined,
    generatedFrom: row.generated_from ? JSON.parse(row.generated_from) : undefined,
    createdAt: row.created_at,
  };
}

/**
 * Convert NewsArticle to database row values
 */
export function articleToRow(article: Omit<NewsArticle, 'id' | 'createdAt'> & { id?: string }): Omit<NewsArticleRow, 'created_at'> & { id: string } {
  return {
    id: article.id || crypto.randomUUID(),
    slug: article.slug,
    source: article.source,
    source_url: article.sourceUrl ?? null,
    source_feed: article.sourceFeed ?? null,
    headline: article.headline,
    subheadline: article.subheadline ?? null,
    summary: article.summary,
    content: article.content,
    category: article.category,
    author: article.author,
    published_at: article.publishedAt,
    updated_at: article.updatedAt ?? null,
    image_url: article.imageUrl ?? null,
    image_caption: article.imageCaption ?? null,
    image_emoji: article.imageEmoji ?? null,
    tags: JSON.stringify(article.tags || []),
    entities: JSON.stringify(article.entities || []),
    sentiment: article.sentiment ?? null,
    npc_mentions: article.npcMentions || 0,
    last_mentioned_at: article.lastMentionedAt ?? null,
    generated_from: article.generatedFrom ? JSON.stringify(article.generatedFrom) : null,
  };
}
