/**
 * GenArt Types
 *
 * Shared type definitions for the generative art engine.
 * These bridge the gap between audio-canvas's real audio data
 * and our procedural driver's synthetic data.
 */

// ============================================================================
// Audio Feature Types (synthetic, generated by ProceduralDriver)
// ============================================================================

export interface AudioFeatures {
  bass: number;              // 0-1, low frequency energy
  mid: number;               // 0-1, mid frequency energy
  high: number;              // 0-1, high frequency energy
  amplitude: number;         // 0-1, overall loudness
  centroid: number;          // 0-1, spectral centroid (pitch character)
  dominantFrequency: number; // 0-1, normalized dominant frequency
  frequencies: Uint8Array;   // Synthetic 1024-bin frequency array
}

export interface BeatInfo {
  onBeat: boolean;           // True for one frame at beat onset
  beatIntensity: number;     // 0-1, how strong this beat is
  bpm: number;               // Beats per minute
  normalizedTempo: number;   // 0-1, where 0=slow(40bpm), 1=fast(200bpm)
  isSaturated: boolean;      // True during sustained high-energy periods
}

// ============================================================================
// Tuner Parameters
// ============================================================================

export interface TunerParams {
  decay: number;        // 0-1, trail length (0=instant clear, 1=long trails)
  sensitivity: number;  // 0-1, reactivity threshold
  feedback: number;     // 0-1, self-reference amount
  bassWeight: number;   // 0-1, bass frequency multiplier
  midWeight: number;    // 0-1, mid frequency multiplier
  highWeight: number;   // 0-1, high frequency multiplier
  colorDrift: number;   // 0-1, hue shift speed over time
  chaos: number;        // 0-1, randomness/unpredictability
}

export const DEFAULT_TUNER_PARAMS: TunerParams = {
  decay: 0.5,
  sensitivity: 0.5,
  feedback: 0.3,
  bassWeight: 0.5,
  midWeight: 0.5,
  highWeight: 0.5,
  colorDrift: 0.3,
  chaos: 0.5,
};

export const TUNER_PRESETS: Record<string, Partial<TunerParams>> = {
  subtle: {
    decay: 0.7,
    sensitivity: 0.3,
    feedback: 0.1,
    bassWeight: 0.4,
    midWeight: 0.5,
    highWeight: 0.4,
    colorDrift: 0.1,
    chaos: 0.1,
  },
  aggressive: {
    decay: 0.3,
    sensitivity: 0.8,
    feedback: 0.5,
    bassWeight: 0.8,
    midWeight: 0.6,
    highWeight: 0.9,
    colorDrift: 0.5,
    chaos: 0.4,
  },
  chaotic: {
    decay: 0.1,
    sensitivity: 1.0,
    feedback: 0.9,
    bassWeight: 1.0,
    midWeight: 1.0,
    highWeight: 1.0,
    colorDrift: 0.8,
    chaos: 1.0,
  },
  dreamy: {
    decay: 0.8,
    sensitivity: 0.3,
    feedback: 0.6,
    bassWeight: 0.4,
    midWeight: 0.6,
    highWeight: 0.3,
    colorDrift: 0.4,
    chaos: 0.2,
  },
};

// ============================================================================
// Energy Curves
// ============================================================================

export type EnergyCurveType =
  | 'steady'
  | 'build_up'
  | 'pulse'
  | 'chaotic'
  | 'calm_to_storm'
  | 'drop'
  | 'breathe';

// ============================================================================
// GenArt Config (stored per video)
// ============================================================================

export interface Keyframe {
  time: number;                    // Seconds into the video
  params: Partial<TunerParams>;    // Params to interpolate to
  easing?: 'linear' | 'ease-in' | 'ease-out' | 'ease-in-out';
}

export interface GenArtConfig {
  mode: string;                    // Mode ID from registry
  tunerParams: TunerParams;
  energyCurve: EnergyCurveType;
  bpm: number;
  pitch: number;                   // 0-1, base color character
  keyframes?: Keyframe[];          // Optional param changes over time
}

// ============================================================================
// Mode Metadata
// ============================================================================

export type ModeCategory = 'abstract' | 'geometric' | 'organic' | '3d';

export interface ModeInfo {
  id: string;
  name: string;
  description: string;
  category: ModeCategory;
  is3D: boolean;
}
